### ISSUE TITLE
Screenshots of GUI?

### ISSUE THREAD

**Issue by jmiahman** [smartpm/smart#3]
Is there anywhere I can get screenshots of the GUIs, ie. GTK and QT. it looks like the readme says only Qt3 but I see a Qt4 option. Doe sthe Readme need to be updated?

**Comment by afb** [comment]
Well, there's some screenshots of the traditional GUI (GTK2 and Qt3) right in the documentation.
https://github.com/smartpm/smart/tree/master/doc/images

The Qt4 port was pretty straightforward, but ended up not being used by the original customer.
It was the only option in the python3 port, but now there's PySide too.
